import Foundation
import Testing
@testable import PaseoIconCore

/// Interop with tweetnacl, which `@getpaseo/relay` wraps. The vectors are
/// generated by `scripts/make-e2ee-fixtures.mjs`; matching their bytes means
/// matching the daemon.
struct E2EEBoxTests {
    struct Fixture: Decodable {
        struct Vector: Decodable {
            let name: String
            let isBinary: Bool
            let daemonPublicKeyB64: String
            let daemonSecretKeyB64: String
            let clientPublicKeyB64: String
            let clientSecretKeyB64: String
            let sharedKeyB64: String
            let nonceB64: String
            let plaintextB64: String
            let bundleB64: String
        }

        let lowOrderPublicKeyB64: String
        let vectors: [Vector]
    }

    static func loadFixture() throws -> Fixture {
        let url = try #require(Bundle.module.url(forResource: "e2ee-vectors", withExtension: "json", subdirectory: "Fixtures"))
        return try JSONDecoder().decode(Fixture.self, from: Data(contentsOf: url))
    }

    static func bytes(_ base64: String) throws -> [UInt8] {
        [UInt8](try #require(Data(base64Encoded: base64)))
    }

    @Test("derives the same shared key tweetnacl derived, from either side")
    func sharedKey() throws {
        for vector in try Self.loadFixture().vectors {
            let expected = E2EESharedKey(bytes: try Self.bytes(vector.sharedKeyB64))
            let client = try E2EEBox.deriveSharedKey(
                ourSecretKey: try Self.bytes(vector.clientSecretKeyB64),
                peerPublicKey: try E2EEBox.importPublicKey(base64: vector.daemonPublicKeyB64)
            )
            let daemon = try E2EEBox.deriveSharedKey(
                ourSecretKey: try Self.bytes(vector.daemonSecretKeyB64),
                peerPublicKey: try E2EEBox.importPublicKey(base64: vector.clientPublicKeyB64)
            )
            #expect(client == expected, "\(vector.name)")
            #expect(daemon == expected, "\(vector.name)")
        }
    }

    @Test("decrypts every tweetnacl bundle")
    func decryptsVectors() throws {
        for vector in try Self.loadFixture().vectors {
            let key = E2EESharedKey(bytes: try Self.bytes(vector.sharedKeyB64))
            let plaintext = try E2EEBox.decrypt(try Self.bytes(vector.bundleB64), with: key)
            #expect(plaintext == (try Self.bytes(vector.plaintextB64)), "\(vector.name)")
        }
    }

    @Test("encrypts to a bundle tweetnacl's layout describes, and round-trips")
    func encryptsRoundTrip() throws {
        for vector in try Self.loadFixture().vectors {
            let key = E2EESharedKey(bytes: try Self.bytes(vector.sharedKeyB64))
            let plaintext = try Self.bytes(vector.plaintextB64)
            let bundle = try E2EEBox.encrypt(plaintext, with: key)
            #expect(bundle.count == plaintext.count + E2EEBox.overheadLength, "\(vector.name)")
            #expect(try E2EEBox.decrypt(bundle, with: key) == plaintext, "\(vector.name)")
        }
    }

    @Test("a tampered bundle does not decrypt")
    func tamperDetected() throws {
        let vector = try #require(try Self.loadFixture().vectors.first { $0.name == "hello-json" })
        let key = E2EESharedKey(bytes: try Self.bytes(vector.sharedKeyB64))
        var bundle = try Self.bytes(vector.bundleB64)
        bundle[bundle.count - 1] ^= 0x01
        #expect(throws: E2EEBoxError.decryptionFailed) { try E2EEBox.decrypt(bundle, with: key) }
    }

    @Test("a bundle shorter than a nonce is rejected before decryption")
    func tooShort() {
        let key = E2EESharedKey(bytes: [UInt8](repeating: 1, count: 32))
        #expect(throws: E2EEBoxError.bundleTooShort(5)) { try E2EEBox.decrypt([1, 2, 3, 4, 5], with: key) }
    }

    @Test("a low-order peer key is refused, as tweetnacl's deriveSharedKey refuses it")
    func lowOrderKey() throws {
        let fixture = try Self.loadFixture()
        let pair = E2EEBox.generateKeyPair()
        #expect(throws: E2EEBoxError.lowOrderPublicKey) {
            try E2EEBox.deriveSharedKey(
                ourSecretKey: pair.secretKey,
                peerPublicKey: try E2EEBox.importPublicKey(base64: fixture.lowOrderPublicKeyB64)
            )
        }
    }

    @Test("public key import checks base64 and length")
    func importChecks() {
        #expect(throws: E2EEBoxError.invalidBase64) { try E2EEBox.importPublicKey(base64: "***") }
        #expect(throws: E2EEBoxError.invalidPublicKeyLength(3)) { try E2EEBox.importPublicKey(base64: "AAAA") }
    }
}
